### Dockerfile -- git server

# El Cid (https://github.com/michipili/cid)
# This file is part of El Cid
#
# Copyright © 2018 Michael Grünewald
#
# This file must be used under the terms of the MIT license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at
# https://opensource.org/licenses/MIT

FROM cid/linux
SCRIPT setup/git-server.sh
CMD ["/usr/sbin/sshd","-D"]
VOLUME ["/var/git"]
