### Dockerfile -- git server

# El Cid (https://github.com/michipili/cid)
# This file is part of El Cid
#
# Copyright © 2018 Michael Grünewald
#
# This file must be used under the terms of the MIT license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at
# https://opensource.org/licenses/MIT

FROM cid/linux

COPY ./docker/setup/gitserver.sh /root/setup/
RUN sh /root/setup/gitserver.sh

COPY ./docker/setup/bsdowl.sh /root/setup/
RUN sh /root/setup/bsdowl.sh

COPY ./docker/image/admin/support.sh /root/setup/
ADD ./support /opt/cid/var/src/support
RUN chown -R cid:cid /opt/cid/var/src/support
RUN sh /root/setup/support.sh

CMD ["/usr/sbin/sshd","-D"]
VOLUME ["/var/git"]
