FROM cid/linux
SCRIPT setup/postgresql.sh
ADD entrypoint /usr/local/bin/entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint"]
CMD ["/usr/lib/postgresql/9.6/bin/postgres","-D","/var/lib/postgresql/9.6/main","-c","config_file=/etc/postgresql/9.6/main/postgresql.conf"]
VOLUME ["/etc/postgresql","/var/lib/postgresql"]
