#!/bin/sh

### compose_tool -- Tool to run docker compose

: ${package:=cid}
: ${packagedir:=/cid}
: ${prefix:=/usr/local}
: ${cachedir:=${prefix}/var/cache${packagedir}}

. './subr.sh'

#
# Main
#

compose_project='local'

compose_main()
{
    local OPTIND OPTION OPTARG image

    status=1
    OPTIND=1

    while getopts 'p:' OPTION; do
        case ${OPTION} in
            p)	compose_project="${OPTARG}";;
            *)	failwith -x 70 'compose_tool: %s: Unsupported option.' "${OPTION}";;
        esac
    done
    shift $(expr ${OPTIND} - 1)

    (
        cid_project="${compose_project}"
        export cid_project

        exec docker-compose\
             --file "./docker_compose.yml"\
             --project-name "cid-${compose_project}"\
             "$@"
    )
}

compose_main "$@"
