#!/bin/sh

### admin_console -- Start the Admin Shell

# El Cid (https://github.com/michipili/cid)
# This file is part of El Cid
#
# Copyright © 2018 Michael Grünewald
#
# This file must be used under the terms of the MIT license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at
# https://opensource.org/licenses/MIT

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}
: ${subrdir:=${TOPLEVELDIR}/subr}
: ${dockerimage:=cid/admin}
: ${admin_package:='cid'}
: ${admin_user:='root'}
: ${admin_interaction:=confirm}

. "${subrdir}/stdlib.sh"
. "${subrdir}/config.sh"

. "${subrdir}/trac.sh"
. "${subrdir}/jenkins.sh"
. "${subrdir}/gitserver.sh"

admin_config()
{
    git config --file "${config_dir}/cid.conf" "$@"
}

admin_docker()
{
    docker run --rm\
           --user "${admin_user}"\
           --volume "cid-${config_project}-jenkins:/var/lib/jenkins"\
           $(admin_docker__volume)\
           --volume "${config_backupdir}:/opt/cid/var/backups"\
           --volume "${config_dir}:/opt/cid/var/config"\
           "$@"
}

admin_docker__volume()
{
    config_volume_db | awk -F '|' '{printf(" --volume %s:%s", $2, $3)}'
}

admin_shell()
{
    admin_docker -it "${dockerimage}" bash -l
}

admin_devshell()
{
    admin_docker\
        --volume "${TOPLEVELDIR}:/opt/cid/var/src/cid"\
        -it "${dockerimage}" bash -l
}

admin_dump()
{
    if ! [ -d "${config_backupdir}" ]; then
        wlog 'Error' 'admin: %s: The backup directory does not exist.' "${config_backupdir}"
        exit 1
    fi
    admin_docker -it "${dockerimage}" cid_dump -p "${config_project}"
}

admin_restore()
{
    local dumpfile shortname
    case "$1" in
        /*)
            dumpfile="$1"
            ;;
        *)
            dumpfile="$(pwd -P)/$1"
            ;;
    esac
    shortname="${dumpfile##*/}"
    if [ -f "${dumpfile}" ]; then
        admin_docker\
            --volume "${dumpfile}:/var/backups/${shortname}"\
            -it "${dockerimage}" cid_restore "/var/backups/${shortname}"
    else
        failwith '%s: Cannot restore, file not found.' "${dumpfile}"
    fi
}

admin_ls()
{
    docker volume ls --format '{{.Name}}'\
        | sed -n -e '
/-git$/{s/^cid-//;s/-git$//;p;}
/-jenkins$/{s/^cid-//;s/-jenkins$//;p;}
/-trac$/{s/^cid-//;s/-trac$//;p;}
/-www$/{s/^cid-//;s/-www$//;p;}
'\
        | sort -u
}

admin_rm()
{
    case "${admin_interaction}" in
        confirm)
            confirm '%s: Remove data volumes for this project.' "${config_project}";;
        yes)
            : 'NOP'
            ;;
        no)
            failwith 'admin_rm: Interaction set to no, abort.'
            ;;
    esac
    docker volume ls --format '{{.Name}}'\
        | grep -F "cid-${config_project}"\
        | xargs docker volume rm
}

admin_create()
{
    local volume
    config_volume_list | while read volume; do
        docker volume create "${volume}"
    done
    docker volume create "cid-${config_project}-jenkins"
}

admin_jenkins()
{
    local version

    version=$(config 'jenkins.version')
    if [ -z "${version}" ]; then
        version="${config_dir%/}"
        version="${version##*/}"
    fi

    if [ -f "${config_dir}/Dockerfile" ]; then
        (
            cd "${TOPLEVELDIR}"
            docker build -t "${admin_package}/jenkins:${version}" -
        ) < "${config_dir}/Dockerfile"
    else
        failwith '%s: Dockerfile for specialised Jenkins image is missing.'
    fi
}



admin_configure()
{
    admin_docker -it "${dockerimage}" cid_configure -p "${config_project}"
}

admin_main()
{
    local OPTIND OPTION OPTARG

    subcommand='shell'
    OPTIND=1

    while getopts 'b:c:dhp:' OPTION; do
        case ${OPTION} in
            c)	config_dir="${OPTARG%/}";;
            p)	config_project="${OPTARG}";;
            b)	config_backupdir="${OPTARG}";;
            d)	admin_subcommand='subshell';;
            h)	admin_usage; exit 0;;
            *)	failwith -x 64 'admin_console: %s: Unsupported option.' "${OPTION}";;
        esac
    done
    shift $(expr ${OPTIND} - 1)
    config_setup

    case "$1" in
        configure|create|dump|ls|restore|rm|jenkins)
            subcommand="$1"
            shift
            ;;
    esac

    admin_${subcommand} "$@"
}

admin_main "$@"

### End of file `admin_console'
