#!/bin/sh

### docker_compose -- Tool to run docker compose

# El Cid (https://github.com/michipili/cid)
# This file is part of El Cid
#
# Copyright © 2018 Michael Grünewald
#
# This file must be used under the terms of the MIT license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at
# https://opensource.org/licenses/MIT

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}
: ${dockerdir:=${TOPLEVELDIR}/docker}
: ${package:=cid}
: ${packagedir:=/cid}
: ${prefix:=/usr/local}
: ${cachedir:=${prefix}/var/cache${packagedir}}
: ${subrdir:=${TOPLEVELDIR}/subr}

. "${subrdir}/stdlib.sh"
. "${subrdir}/config.sh"

#
# Main
#

compose_jenkinsversion()
{
    docker images --format '{{.Repository}}:{{.Tag}}' |\
        awk -F ':'\
            -v project="${config_project}" '
BEGIN {
 version = "latest"
}

$1 == "cid/jenkins" && $2 == project {
 version = $2
}

END {
 print version
}'
}

compose_main()
{
    local OPTIND OPTION OPTARG
    local compose_environment

    compose_environment='cid'

    status=1
    OPTIND=1

    while getopts 'hc:p:e:' OPTION; do
        case ${OPTION} in
            e)	compose_environment="${OPTARG}";;
            c)	config_dir="${OPTARG%/}";;
            p)	config_project="${OPTARG}";;
            *)	failwith -x 70 'docker_compose: %s: Unsupported option.' "${OPTION}";;
        esac
    done
    shift $(expr ${OPTIND} - 1)
    config_setup

    (
        cid_project="${config_project}"
        cid_jenkinsversion="$(compose_jenkinsversion)"
        export cid_project
        export cid_jenkinsversion

        if ! [ -f "${dockerdir}/compose/${compose_environment}.yml" ]; then
            failwith -x 64 'docker_compose: %s: Nothing is known about this environment.' "${compose_environment}"
        fi

        exec docker-compose\
             --file "${dockerdir}/compose/${compose_environment}.yml"\
             --project-name "${package}_${config_project}"\
             "$@"
    )
}

compose_main "$@"

### End of file `docker_compose'
