#!/bin/sh

### generate_cid_conf_md -- Generate the cid_conf.md documentation

# El Cid (https://github.com/michipili/cid)
# This file is part of El Cid
#
# Copyright © 2018 Michael Grünewald
#
# This file must be used under the terms of the MIT license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at
# https://opensource.org/licenses/MIT

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}


generate_filter()
{
    cat <<EOF
# cid.conf — Project configuration

~~~ conf
EOF
    cat -
cat <<EOF
~~~
EOF
}

generate_filter < "${TOPLEVELDIR}/example/cid.conf" > "${TOPLEVELDIR}/doc/cid.conf.md"
