#!/bin/sh

# El Cid (https://github.com/michipili/cid)
# This file is part of El Cid
#
# Copyright © 2018 Michael Grünewald
#
# This file must be used under the terms of the MIT license.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at
# https://opensource.org/licenses/MIT

set -e

if [ "${1#-}" != "$1" ]; then
  # First arg is `-F` or `--SOME-OPTION`
  set -- haproxy "$@"
fi

exec "$@"
